INSERT INTO Generos (id, nome) VALUES
    (1,'Aventura'),
    (2,'Fantasia'),
    (3,'Animação'),
    (4,'Drama'),
    (5,'Terror'),
    (6,'Ação'),
    (7,'Comédia'),
    (8,'História'),
    (9,'Faroeste'),
    (10,'Thriller'),
    (11,'Crime'),
    (12,'Documentário'),
    (13,'Ficção científica'),
    (14,'Mistério'),
    (15,'Música'),
    (16,'Romance'),
    (17,'Família'),
    (18,'Guerra'),
    (19,'Cinema TV');